### ISSUE TITLE
Possibly wrong memory configuration for stm32f40x

### ISSUE THREAD

**Issue by ruabmbua** [bobbin-rs/bobbin-sdk#3]
https://github.com/bobbin-rs/bobbin-sdk/blob/cd9a345c53b6b51f99b9542ea8be50baaf61abba/mcu/bobbin-stm32/stm32f40x/link/stm32f40xg.x#L5

The MCU`s have 64KB of CCM SRAM
and 112+16KB = 128KB of SRAM.

**Comment by jcsoo** [comment]
Thanks for catching that. If you come across any other issues in the future, please include a link to the datasheet so that we have a reference. 

In this case the proper memory map is described in Figure 18 of the datasheet.

http://www.st.com/content/ccc/resource/technical/document/datasheet/ef/92/76/6d/bb/c2/4f/f7/DM00037051.pdf/files/DM00037051.pdf/jcr:content/translations/en.DM00037051.pdf
